version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Change this to a secure password
      MYSQL_DATABASE: my_database        # Replace with your database name
      MYSQL_USER: user                   # Replace with your username
      MYSQL_PASSWORD: userpassword       # Replace with your password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
